### ISSUE TITLE
[Refactor] 개인 일정 리펙토링 

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#134]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
Fragment, Activity에 있는 기존의 로직들은 ViewModel, Repository로 옮긴다.

## **Todo**

- [x] 개인 일정 추가 리펙토링
- [x] 개인 일정 수정 리펙토링
- [x] 개인 일정 삭제 리펙토링
- [ ] 개인 일정 조회 리펙토링
- [ ] 서버 업로드 확인
