### ISSUE TITLE
[Refactor] 개인 기록 리팩토링

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#135]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
Fragment, Activity에 있는 UI 로직을 제외한 코드들을 ViewModel, Repository 등으로 옮겨서 MVVM 패턴 구현

## **Todo**

- [x] 개인 기록 추가/수정/삭제 리팩토링
