### ISSUE TITLE
[Refactor] 룸디비 리펙토링

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#142]
## Type of change

- [x] Refactor : 코드 리팩토링 작업
- [x] Style : 코드 스타일 및 포맷팅 작업

## **Description**

- 테이블명 스네이크케이스 적용
- 필드명 카멜케이스 적용
- idx를 id로 통일
- Event -> Schedule

## **Todo**

- [x] 일정
- [x] 기록
- [x] 카테고리
- [x] 그룹은 룸디비에서 삭제

## **Reference(Optional)**
- [리펙토링 TODO](https://mynamo.notion.site/71c399e762234858991d0315e8d7ae05?pvs=4)
