### ISSUE TITLE
[Refactor] 카테고리 enum class로 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#151]
## Type of change

- [x] Refactor : 코드 리팩토링 작업

## **Description**

기존 colors.xml에서 사용하던 Color Array를 enum class로 관리하려고자 합니다.

## **Todo**

- [x] 색상 정보 colors.xml -> enum class로 옮기기
- [x] 룸디비에 카테고리 색상 paletteId로 저장하기
- [x] paletteId로 hex 색상 반환하는 메서드 구현하기
