### ISSUE TITLE
[Refactor] 카테고리 리팩토링

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#155]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 카테고리를 클린 아키텍쳐 구조로 리팩토링할 예정입니다.
- 카테고리 조회가 사용되는 부분이 많아서, UseCase를 만들겠습니다.

## **Todo**

- [x] 카테고리 생성
- [x] 카테고리 수정
- [x] 카테고리 삭제
- [x] 카테고리 조회

## **Reference(Optional)**

- 카테고리 조회가 일정, 기록에도 많이 쓰여서 File Changes가 많이 생길 것 같습니다.
