### ISSUE TITLE
[Refactor] 패키지 구조 및 파일명 공사

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#167]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 패키지 구조를 보기 더 쉽게 나눕니다.
- 파일명을 네이밍 규칙에 맞게 정리합니다.
- 리팩토링 하면서 필요없어진 remote 관련 파일을 정리합니다.

## **Todo**

- [x] utils 패키지를 presentation 패키지와 분리 (data, domain, presentation 중에서 쓰이는 곳)
- [x] bottom 패키지 안의 schedule, diary, group, custom과 category를 presentation으로 빼기
- [x] api 인터페이스 명칭 통일
- [x] 개인의 모임 일정, 기록과 그룹의 모임 일정, 기록 분리
- [x] 통신 관련 data class 명칭 통일
- [x] 안 쓰는 remote의 view와 service 파일 삭제
