### ISSUE TITLE
[Chore] 서버 엔드포인트 및 모델 변경 대응

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#177]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

Swagger API 수정에 따른 작업을 진행합니다.

## **Todo**

- [x] Auth
- [x] Schedule
- [x] Diary
- [x] Category
- [x] Group

## **Reference(Optional)**

- [Swagger 세팅을 위한 수정사항 정리](https://www.notion.so/mynamo/Swagger-531e27df31a14a8fa7cd877cd38e49c4?pvs=4)
