### ISSUE TITLE
[Refactor] 모임 메모/모임 기록 api 연동

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#189]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모임 메모, 모임 기록 삭제 api 연동
- 삭제 완료 됐음에도 finish가 안되는 버그 수정
- 모임 메모 -> 모임 기록 경로로 화면 이동했을 경우 모임 기록 삭제 시 화면 이동 로직

## **Todo**

- [x] 모임 메모, 모임 기록 삭제 api 연동
- [x] 삭제 완료 됐음에도 finish가 안되는 버그 수정
- [x] 모임 메모 -> 모임 기록 경로로 화면 이동했을 경우 모임 기록 삭제 시 화면 이동 로직
