### ISSUE TITLE
[Design] 빈 화면 디자인 변경에 따른 UI 수정

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#191]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 디자인이 바뀐 빈 화면에 대해 디자인 대로 UI를 수정합니다.

## **Todo**

- 일정
   - [x] 개인 캘린더
   - [x] 그룹 캘린더
- [x] 커스텀

## **Reference(Optional)**

- 네트워크가 끊겼을 때는 조금 더 생각해봐야 할 것 같습니다.
