### ISSUE TITLE
[Refactor] 모임 일정 hasDiary에 따른 기록 아이콘 표시

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#194]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- hasDiary가 null, false, true일 때의 각각의 처리
- 현재 룸디비의 데이터와 대조하여 기록 아이콘을 표시하는 부분을 서버에서 받아온 hasDiary 값을 통해 대체

## **Todo**

- [x] null일 때 아이콘 표시 X
- [x] false일 때 회색 아이콘 표시
- [x] true일 때 주황색 아이콘 표시

## **Reference(Optional)**

<img width="861" alt="image" src="https://github.com/Namo-Mongmong/Android/assets/101113025/5315784b-3562-4abd-99c0-75a1b961b267">
