### ISSUE TITLE
[Design] 그룹 디자인 변경 적용

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#196]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 그룹 설정 디자인 변경사항 적용
- 그룹 empty처리

## **Todo**

- [x] 그룹 설정 디자인 변경사항 적용
- [x] 그룹 empty처리
