### ISSUE TITLE
[Fix] 기간 일정 아이템의 시간 표시 방식 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#198]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 단일 일정(하루의 일정)일 경우
    1. 시작-종료 시간으로 표기 (ex. 8:00 - 9:00)
- 기간 일정일 경우 (interval 1 이상)
    1. 시작일: 시작 시간 - 23:59
    2. 중간일: 00:00 - 23:59
    3. 종료일: 00:00 - 종료 시간

## **Todo**

- 개인 캘린더
  - [x] 개인 일정
  - [x] 모임 일정
- 그룹 캘린더
  - [x] 개인 일정
  - [x] 모임 일정

## **Reference(Optional)**

- https://mynamo.notion.site/2ddbdbff1ce6464f9ab534633c72a507?pvs=4
