### ISSUE TITLE
[Design] 기록 empty 처리, 날짜 시간 표시

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#203]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 기록, 모임 기록 empty 처리
- 기록 수정/추가 화면에서 날짜의 시간까지 표시

## **Todo**

- [x] 기록 empty 처리
- [x] 모임 기록 empty/네트워크 미연결 처리
- [x] 기록 수정/추가 화면에서 날짜의 시간까지 표시
