### ISSUE TITLE
[Bug] 일정 바텀시트 좌우의 공간 삭제

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#210]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

<img width="327" alt="" src="https://github.com/Namo-Mongmong/Android/assets/101113025/697b5f6b-92fe-4c1e-9bec-24eb4c42cdda">

- 현재 바텀시트 좌우로 공간이 있는데, 피그마 디자인대로 화면에 꽉 맞도록 변경합니다.

## **Todo**

- [x] 화면에 꽉 차도록 바텀시트 공간 확대
