### ISSUE TITLE
[Refactor] 일정, 기록, 카테고리 로컬 저장 코드 삭제

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#254]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 메인 엑티비티의 로컬 저장 코드를 삭제합니다.

## **Todo**

- [x] 메인 액티비티 로컬 저장 코드 삭제
- [x] 예전 레거시 서버 통신 파일 삭제
