### ISSUE TITLE
[Feat] 기록/모임기록 이미지 개별 삭제 추가, 이미지 상세보기 화면

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#258]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 기록에서 이미지를 가져올 때 추가되는 방식으로 로직 변경
- 기록 이미지 개별 삭제 추가
- 이미지 상세보기 화면 추가

## **Todo**

- [x] 모임기록 이미지 개별 삭제 추가
- [x] 기록 이미지 개별 삭제 추가
- [x] 기록 이미지 상세보기 화면
