### ISSUE TITLE
[Feat] BaseURL remote config 값 가져오기

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#278]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- remote config에 서버 주소를 저장하고, 해당 서버 주소를 불러와 API 통신을 진행합니다.

## **Todo**

- [ ] remote config에 baseURL 추가
- [ ] 파이어베이스에서 baseURL 주소 불러오기
- [ ] 불러온 주소로 API 통신 진행
