### ISSUE TITLE
[Refactor] 카테고리 화면 이동 및 데이터 전달 방식 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#286]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

카테고리 화면 이동과 데이터 전달 방식을 수정합니다.

## **Todo**

- [ ] navigation으로 화면 이동
- [ ] args를 통해 '카테고리 조회 -> 수정 화면'으로 데이터 전달
