### ISSUE TITLE
[Feat] 약관 동의 체크 여부에 따라 약관 동의 화면 노출

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#290]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

로그인의 response로 오는
```
"terms": [
      {
        "content": "TERMS_OF_USE",
        "check": false
      },
      {
        "content": "PERSONAL_INFORMATION_COLLECTION",
        "check": false
      }
    ]
```
로 check 항목이 하나라도 false라면 약관 동의 화면 띄우기

## **Todo**

- [ ] 로그인 response로 terms 추가
- [ ] terms의 체크 항목을 확인하여 약관 화면 띄우기
