### ISSUE TITLE
[Feat] v2 일기 리스트 화면, 캘린더 화면 구현

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#294]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 기록페이지를 첫번째 탭으로 변경
- v2 일기 리스트 화면 변경
- v2 일기 캘린더 화면 구현

## **Todo**

- [x] 기록페이지를 첫번째 탭으로 변경
- [x] v2 일기 리스트 화면 변경
- [x] v2 일기 캘린더 화면 구현
