### ISSUE TITLE
[Refactor] 로그인 및 회원탈퇴 API 통합

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#295]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 변경 전: SocialType 별로 로그인/회원탈퇴 API가 따로 존재
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/519e38f8-fd13-4879-be53-bdc976741374">

- 변경 후: 같은 로그인/회원탈퇴 API에서 SocialType으로 구분
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/415f8156-a59b-48c1-9903-cdcbacbadcab">
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/91e17f5f-043d-41c9-b48a-b65ef22415e9">

## **Todo**

- [x] 로그인 API 통합
- [x] 회원탈퇴 API 통합
