### ISSUE TITLE
[Style] 텍스트 및 색상 디자인 시스템 적용

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#297]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

1. 폰트 TextStyle 추가
<img width="573" alt="image" src="https://github.com/user-attachments/assets/206d7ed9-711b-41a6-9ba4-56510588d596">

2. ColorStyle 적용
<img width="405" alt="image" src="https://github.com/user-attachments/assets/b1a0d82b-e847-4188-9b19-a8289b6b5ac3">
<img width="403" alt="image" src="https://github.com/user-attachments/assets/26366123-9046-4a7d-951e-8c27bfc37a78">

## **Todo**

- [x] pretendard 폰트 추가
- [x] TextStyle 추가
- [x] ColorStyle 적용
