### ISSUE TITLE
[Refactor] v2 바텀네비 탭 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#301]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

![image](https://github.com/user-attachments/assets/3925ebad-3d20-4f06-bfc5-f21ca3b5058a)

## **Todo**

- [x] 탭 아이템 변경
- [x] 폴더 구조 변경
