### ISSUE TITLE
[Feat] v2 커뮤니티 탭 작업

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#303]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

<img width="783" alt="image" src="https://github.com/user-attachments/assets/1bda887e-ccb6-4565-9501-3fb9f5476e20">

## **Todo**

- 커뮤니티
   - [x] 탭 레이아웃 연결
   - [x] 모임 일정 화면 UI 구현
   - [x] 친구 리스트 화면 UI 구현
- 알림
   - [x] 탭 레이아웃 연결
   - [x] 모임 요청 화면 UI 구현
   - [x] 친구 요청 화면 UI 구현
- 모임
   - [x] 모임 일정 생성/편집 화면 구현
   - [x] 모임 참석자 정보 다이얼로그 구현
   - [x] 친구 초대 화면 구현
   - [x] 게스트 초대 다이얼로그 구현
   - [x] 모임 캘린더 구현 (친구 일정 캘린더와 공통으로 사용)
- 친구
   - [x] 친구 정보 다이얼로그 구현
   - [x] 새 친구 초대 다이얼로그 구현
   - [x] 친구 일정 캘린더 구현 (모임 캘린더와 공통으로 사용)
