### ISSUE TITLE
[Feat] 기록 캘린더 api 연동

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#310]
## Type of change

- [x] Feature : 새로운 기능 추가

## **Description**

- 기록 캘린더 api 연동
- 기록 캘린더 ui 디테일 수정

## **Todo**

- [ ] 기록 캘린더 api 연동
- [ ] 기록 캘린더 ui 디테일 수정
