### ISSUE TITLE
[Refactor] 기록 패키지 구조 리팩토링

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#316]
## Type of change

- [x] Refactor : 코드 리팩토링 작업

## **Description**

- 개인 기록 화면별 패키징
- 모임 기록 패키지 생성

## **Todo**

- [ ] 개인 기록 화면별 패키징
- [ ] 모임 기록 패키지 생성
