### ISSUE TITLE
[Refactor] 일정 시작일/종료일 API 요청 및 응답 자료형 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#321]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

서버에서 unix 시간 형식에서 String 포맷으로 변환된 부분에 대해 대응합니다.

## **Todo**

- [x] DTO에서는 String 날짜 사용
- [x] Model에서는 LocalDateTime 날짜 사용
- [x] 날짜 계산 방식 내부적으로 Long -> LocalDateTime으로 로직 변경
- [x] 변환 메서드 작성
