### ISSUE TITLE
[Feat] 모임 기록 디자인 수정 적용, 비즈니스로직 구현

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#323]
## Type of change

- [x] Feature : 새로운 기능 추가

## **Description**

- 모임 기록 디자인 수정 (편집 모드 추가)
- 모임 기록 비즈니스 로직 구현

## **Todo**

- [x] 모임 기록 디자인 수정 (편집 모드 추가)
- [x] 모임 기록 비즈니스 로직 구현
