### ISSUE TITLE
[Feat] 보관함 캘린더 수정된 디자인 구현

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#330]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Refactor : 코드 리팩토링 작업

## **Description**

- 보관함 캘린더 기록있는 날 표시 디자인 수정
- 1일 표시 수정
- 생일 개인기록 추가

## **Todo**

- [ ] 보관함 캘린더 기록있는 날 표시 디자인 수정
- [ ] 1일 표시 수정
- [ ] 생일 개인기록 추가
