### ISSUE TITLE
[Refactor] 패키지 구조 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#334]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 클린 아키텍처와 맞지 않는 전체적인 패키지 구조를 정리하고, 안 쓰는 파일을 삭제한다

## **Todo**

- [x] 클린 아키텍처에서 위배되는 파일 위치 이동
- [x] model 파일명 네임 규칙 적용
- [x] usecase 도메인 별로 한번 더 나누기
- [x] 룸디비 잔재 적출
- [x] utils 안에 converter 폴더 분리
