### ISSUE TITLE
[Chore] 카테고리 데이터 변경

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#337]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 디자인대로 내부에 저장된 카테고리 데이터를 변경합니다.
![image](https://github.com/user-attachments/assets/9f3c5f36-d037-4e12-aa8b-39f93f61f500)

## **Todo**

- [ ] 기존 PaletteType 삭제
- [ ] CategoryColor 색상 변경
