### ISSUE TITLE
[Refactor] 생성 수정 삭제 에러 핸들링

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#340]
## Type of change

- [x] Refactor : 코드 리팩토링 작업

## **Description**

- 오류 시에 에러 메세지 전달 로직 구현
- 로직 확장 함수화

## **Todo**

- [ ] 생성 수정 삭제 에러 핸들링
- [ ] 로직 확장 함수화
