### ISSUE TITLE
[Feat] 카테고리 UI 수정 및 API 연동

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#346]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 카테고리 UI 수정 및 API 연동
![image](https://github.com/user-attachments/assets/c02b2e23-defd-4be8-82df-d5ae80139acc)

## **Todo**

- API 연동
  - [x] 카테고리 생성
  - [x] 카테고리 수정
  - [x] 카테고리 삭제
- [x] UI 수정
