### ISSUE TITLE
[Feat] 모임 일정 친구 초대 기능 구현

### ISSUE THREAD

**Issue by nahy-512** [Namo-log/Android#347]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모임 일정 최초 생성 시에는 친구 초대를 진행하지 않고, 생성이 완료되면 친구 초대를 유도하는 팝업을 띄웁니다.
![image](https://github.com/user-attachments/assets/3c114d84-7c87-4e47-99a5-08c9d9c8121e)

- 모임 일정 편집 시 로직을 구현합니다.
![image](https://github.com/user-attachments/assets/0941d04a-bdf5-49bb-9815-c1e9c906a342)

## **Todo**

- [ ] 모임 일정 최초 생성
- [ ] 모임 일정 편집
