### ISSUE TITLE
[Feat] 보관함 캘린더 디자인 수정

### ISSUE THREAD

**Issue by edv-Shin** [Namo-log/Android#348]
## Type of change

- [x] Feature : 새로운 기능 추가

## **Description**

- 보관함 캘린더 스크롤 시 텍스트 색 변환 로직 추가
- 1일 표시 디자인 변경

## **Todo**

- [x] 보관함 캘린더 스크롤 시 텍스트 색 변환 로직 추가
- [x] 1일 표시 디자인 변경
